### ISSUE TITLE
小白求助！扫码后不久就终止抛出异常「附详细日志」    TypeError: this.job.execute is not a function

### ISSUE THREAD

**Issue by AnthonyCoder** [leochen-g/wechatBot#35]
`
当前容器时间:Wed Jul 14 2021 12:54:26 GMT+0800 (China Standard Time)

已开启机器人自动聊天模式

已经设定每日说任务

你的贴心小助理开始工作啦！

TypeError: this.job.execute is not a function

at Job.invoke (/bot/node_modules/node-schedule/lib/schedule.js:177:14)

at /bot/node_modules/node-schedule/lib/schedule.js:555:26

at Timeout._onTimeout (/bot/node_modules/node-schedule/lib/schedule.js:512:7)

at listOnTimeout (internal/timers.js:557:17)

at processTimers (internal/timers.js:500:7)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! wechatbot@0.2.1 start: `node index.js`

npm ERR! Exit status 1



npm ERR!

npm ERR! Failed at the wechatbot@0.2.1 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR! /bot/.npm/_logs/2021-07-14T04_55_00_153Z-debug.log
`

**Comment by AnthonyCoder** [comment]
我是在Mac上面使用Docker部署的
环境：
Node.js v14.17.1
Docker version 20.10.2

启动命令：
docker run --name=chatBot --volume="$(pwd)/config/":/bot/config aibotk/wechat-bot

**Comment by leochen-g** [comment]
拉取一下最新的docker镜像，之前build的镜像有点问题

**Comment by leochen-g** [comment]
正在构建最新的镜像解决这个问题

**Comment by AnthonyCoder** [comment]
> 正在构建最新的镜像解决这个问题

好的 我昨天碰见这个问题就是使用的最新构建的,解决完了烦请通知下,我pull下来再测试下,谢谢啦~

**Comment by leochen-g** [comment]
最新镜像已经更新了

**Comment by atjshop** [comment]
最注册的微信号也可以用这个吗？

**Comment by leochen-g** [comment]
> 最注册的微信号也可以用这个吗？

可以的，最新的web协议是UOS桌面版的，都可以用
