### ISSUE TITLE
ducker第二步修改config文件怎么操作鸭?

### ISSUE THREAD

**Issue by jesee030** [leochen-g/wechatBot#36]
window10系统枯了

**Comment by leochen-g** [comment]
把代码拉下来操作奥

**Comment by lywly** [comment]
将[`index.js`](https://github.com/leochen-g/wechatBot/blob/master/config/index.js)文件拷贝至服务器根目录的`config`文件夹下，修改相应配置就行。
`--volume="$(pwd)/config/":/bot/config`这个命令就会让docker容器自动映射到宿主机的`index.js`文件
