### ISSUE TITLE
网页版无法登陆、如何解决

### ISSUE THREAD

**Issue by 936447225** [leochen-g/wechatBot#39]
} message:为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

**Comment by 936447225** [comment]
各位有碰到这个问题吗

**Comment by leochen-g** [comment]
是登录后 退出重新扫码出现的么，如果是的话话重新拉一下代码跑一下，最新的puppet已经解决这个问题了 
https://github.com/wechaty/wechaty-puppet-wechat/issues/140

**Comment by 936447225** [comment]
了解 我试试

**Comment by MengxingLiu** [comment]
我下载的最新的代码和container
Docker Container for Wechaty v0.63.3 with Node.js v14.17.1 ...
 wechatbot@0.2.2 start /bot

但是还是网页版无法登录，提示：你的帐号无法登录网页版wechat,可改用windows版wechat或者mac版wechat.

**Comment by leochen-g** [comment]
目前已经可以正常使用uos协议了
