### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by Dachuizi-6** [leochen-g/wechatBot#44]
现在最新版的更新之后不能登录是咋回事呀

**Comment by Dachuizi-6** [comment]
那微信就不能登陆了嘛？有什么解决方案不



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月5日(周三) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leochen-g/wechatBot] 登录问题 (Issue #44)




 
腾讯在uos上架了新版微信，不再是以前的网页版套壳了，所以之前的伪装uos微信登录失效了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leochen-g** [comment]
> 那微信就不能登陆了嘛？有什么解决方案不
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月5日(周三) 晚上10:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [leochen-g/wechatBot] 登录问题 (Issue #44) 腾讯在uos上架了新版微信，不再是以前的网页版套壳了，所以之前的伪装uos微信登录失效了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

目前只能使用之前的web协议，或者自己申请ipadlocal 的token

**Comment by Dachuizi-6** [comment]
我这个是web协议吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月6日(周四) 上午9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leochen-g/wechatBot] 登录问题 (Issue #44)




  
那微信就不能登陆了嘛？有什么解决方案不
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年1月5日(周三) 晚上10:57 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [leochen-g/wechatBot] 登录问题 (Issue #44) 腾讯在uos上架了新版微信，不再是以前的网页版套壳了，所以之前的伪装uos微信登录失效了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
目前只能使用之前的web协议，或者自己申请ipadlocal 的token
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 156874** [comment]
是不是现在还是无法登陆啊

**Comment by Dachuizi-6** [comment]
是的，我登录不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月17日(周一) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leochen-g/wechatBot] 登录问题 (Issue #44)




 
是不是现在还是无法登陆啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leochen-g** [comment]
现在已经可以登录了，拉取最新代码查看
