### ISSUE TITLE
已经使用token了，配置如下，但是登录依旧出了问题，是从docker中下载的

### ISSUE THREAD

**Issue by club3org** [leochen-g/wechatBot#45]
<img width="747" alt="2a8207877bead56e30b1057034211e2" src="https://user-images.githubusercontent.com/38119954/149626495-96999b9f-139e-4180-8c7b-31bf261f08d7.png">
<img width="744" alt="ebd97988bdd771640064fa48b2e4ae9" src="https://user-images.githubusercontent.com/38119954/149626511-5788bb5d-18c0-40d3-8643-b15866acbed3.png">
有看到package中wechat改变，但是更改以后没有太大效果，期待您的回复和帮助

**Comment by leochen-g** [comment]
拉取最新版docker查看，另外请不要暴露你的token，这是很危险的行为，默认web协议是不需要填写token的
