### ISSUE TITLE
有一个代码设计方面的问题向您请教

### ISSUE THREAD

**Issue by yzh1255245824** [leochen-g/wechatBot#46]
我注意到您的`package.json`中采用的是**wechaty@0.60.10**，由此我发现一个问题，就是通过`new Wechaty`创建的bot实例，在调用`bot.on()`方法注册监听时，第二个参数字段无法使用字符串（我之前使用的0.38.4是可以的）。

因此我无法将监听逻辑单独封装在一个文件中再导入入口文件，而必须与入口文件写在一起。例如以下这种写法将不被允许：
`bot.on("message", "./listeners/on-message");`

因为我的`message`监听事件有将近500行代码，这样就会导致我的入口文件代码量十分冗杂，不知道这个问题您是否遇到过呢？希望能给我一些启发。对于我造成的任何困扰，我在此感到抱歉！

**Comment by leochen-g** [comment]
这个建议你升级版本了要，因为更新了太多功能了，现在1.x版本可以考虑更换一下的

**Comment by leochen-g** [comment]
如果没有其他问题，我就先关闭这个issues 了
