### ISSUE TITLE
uos协议中是不是监测不到退群

### ISSUE THREAD

**Issue by mengpf** [leochen-g/wechatBot#55]
uos协议中是不是监测不到退群，看到WeChaty官方有Api，Room event:leave

**Comment by hfcheng66** [comment]
uos还可以登录吗，你用的是比较老的微信号还是新微信号？

**Comment by mengpf** [comment]
> 

uos现在又可以用了，据说新号也可以。

**Comment by leochen-g** [comment]
退群的话只有机器人是群管或者群主的时候才能监听到

**Comment by mengpf** [comment]
> 退群的话只有机器人是群管或者群主的时候才能监听到

了解了，谢谢。
